/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const AppConfig = t.iface([], {
  "botToken": "string",
  "wiLockApplicationId": "string",
  "wiLockLogin": "string",
  "wiLockPass": "string",
  "wiLockDeviceId": "string",
  "wiLockDeviceSwitchName": "string",
  "allowedGroupId": "number",
  "discordBotId": "string",
  "discordBotToken": "string",
  "discordAllowedGroupId": "string",
});

const exportedTypeSuite: t.ITypeSuite = {
  AppConfig,
};
export default exportedTypeSuite;
